# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoplate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 558)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(6, 6, 831, 551))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(831, 551))
        self.frame.setMaximumSize(QtCore.QSize(831, 551))
        self.frame.setStyleSheet("background-color: rgb(237, 237, 237);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(7, 6, 811, 211))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(40, 40, 191, 131))
        self.frame_4.setStyleSheet("image: url(:/logo/logo.png);\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(280, 10, 471, 161))
        self.label_9.setStyleSheet("font: 28pt \"Segoe MDL2 Assets\";")
        self.label_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_9.setText("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(-10, 230, 431, 130))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 10, 111, 71))
        self.label.setStyleSheet(" \n"
"image: url(:/webcam/webcam.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(190, 30, 161, 21))
        self.label_5.setStyleSheet("font: 12pt \"Trebuchet MS\";")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(100, 89, 131, 31))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover#pushButton\n"
"{\n"
"  background-color: rgb(0, 197, 95);\n"
" \n"
" }")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 89, 121, 31))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover#pushButton_2\n"
"{\n"
"  background-color: rgb(0, 197, 95);\n"
" \n"
" }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(430, 230, 391, 130))
        self.frame_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 111, 71))
        self.label_2.setStyleSheet(" \n"
"image: url(:/add/add-file.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setGeometry(QtCore.QRect(110, 30, 151, 21))
        self.label_6.setStyleSheet("font: 12pt \"Trebuchet MS\";")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 90, 101, 31))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 170, 127);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover#pushButton_3\n"
"{\n"
"  background-color: rgb(0, 197, 95);\n"
"  \n"
" }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(-20, 370, 441, 130))
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_3 = QtWidgets.QLabel(self.frame_6)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 121, 71))
        self.label_3.setStyleSheet("image: url(:/search/search.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(130, 30, 281, 51))
        self.label_7.setStyleSheet("font: 12pt \"Trebuchet MS\";")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 90, 141, 31))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 44, 2);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover#pushButton_4\n"
"\n"
"{\n"
"   \n"
"    background-color: rgb(255, 85, 0);\n"
" \n"
" }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(430, 370, 391, 130))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setGeometry(QtCore.QRect(280, 0, 121, 71))
        self.label_4.setStyleSheet("image: url(:/update/diagnosis.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_7)
        self.label_8.setGeometry(QtCore.QRect(130, 30, 151, 21))
        self.label_8.setStyleSheet("font: 12pt \"Trebuchet MS\";")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_5.setGeometry(QtCore.QRect(150, 90, 101, 31))
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setStyleSheet("QPushButton{  \n"
"    background-color: rgb(0, 124, 186);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 12pt \"Yu Gothic UI Semibold\";\n"
"}\n"
"\n"
"QPushButton:hover#pushButton_5\n"
"{\n"
"    background-color: rgb(0, 170, 255);\n"
"   \n"
" }")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(150, 510, 561, 31))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", " INPUT A CAR PICTURE"))
        self.pushButton.setToolTip(_translate("MainWindow", "select a vehicle picture"))
        self.pushButton.setText(_translate("MainWindow", "SELECT PICTURE"))
        self.pushButton_2.setToolTip(_translate("MainWindow", "use camera to detect plate"))
        self.pushButton_2.setText(_translate("MainWindow", "TAKE PICTURE"))
        self.label_6.setText(_translate("MainWindow", " INPUT A CAR PLATE"))
        self.pushButton_3.setToolTip(_translate("MainWindow", "Enter a car plate manually"))
        self.pushButton_3.setText(_translate("MainWindow", "ENTER"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>SEARCH &amp; DELETE CAR </p><p>PLATE</p></body></html>"))
        self.pushButton_4.setToolTip(_translate("MainWindow", "Search or Delete a car Plate"))
        self.pushButton_4.setText(_translate("MainWindow", "SEARCH / DELETE"))
        self.frame_7.setToolTip(_translate("MainWindow", "Update vehical details in the db"))
        self.label_8.setText(_translate("MainWindow", "UPDATE CAR DETAILS"))
        self.pushButton_5.setText(_translate("MainWindow", "UPDATE"))
        self.label_10.setText(_translate("MainWindow", " <p>&copy; Kamati Technologies</p>"))
import add_rc
import delete_rc
import logo_rc
import search_rc
import update_rc
import webcam_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
